### PR TITLE
Implement read and create benchmark in Nextras ORM

### PR DESCRIPTION
**Pull request by repli2dev**
Hi, I have implemented the tests create and read in Nextras ORM (https://github.com/sergeyklay/php-orm-benchmark/issues/23).

### CODE REVIEW

**Comment by sergeyklay** [comment]
@repli2dev Could you please README.md? You'll need to amend table with results and build id from the Travis CI

**Comment by repli2dev** [comment]
@sergeyklay I will do, however I am having some troubles making it work on Travis CI as I am getting: `Nextras\Dbal\QueryException: Unknown or incorrect time zone: 'UTC' on /home/travis/build/sergeyklay/php-orm-benchmark/provider/nextrasorm/vendor/nextras/dbal/src/Drivers/Mysqli/MysqliDriver.php:381` which typically means that I need to add timezones to the MySQL and I don't know the prefered way.

**Comment by sergeyklay** [comment]
@repli2dev 

The known approach to fix it is add this command to **`before_script`** section:

```bash
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
```

Have a nice day

**Comment by repli2dev** [comment]
@sergeyklay Now it has executed properly, however I am a bit puzzled which results are which in the CI to update the README.

**Comment by sergeyklay** [comment]
@repli2dev Let me update results a bit later. Thank you for the contributing, and for helping make  benchmark better.

**Comment by repli2dev** [comment]
Thanks... Ping me when other operations will need implementation.

**Pull request merged**
