### PR TITLE
Move to separate folder

### LINKED ISSUE #10: Split providers to its own folder
Hi, 

Have you thought of splitting the providers to its own folder and having an independent composer.json file ?

Else I wonder whether the memory consumption of different components by composer autoload have some effect.

### PR DESCRIPTION
**Pull request by harikt**
Partially fixed https://github.com/sergeyklay/php-orm-benchmark/issues/10 .

The docker file need to be updated.

I am not familiar with it.

I think probably each repo should contain a separate docker file for the phalcon extension is not needed for the rest.

### CODE REVIEW

**Comment by harikt** [comment]
May be we need to run benchmarks on travis ;) .

**Comment by sergeyklay** [comment]
@harikt Absolutely. With Travis CI we don't need to launch Docker.

**Comment by sergeyklay** [comment]
Thank you

**Comment by harikt** [comment]
@sergeyklay this is not fully done or may be broken on docker. May be you need to verify the same .

**Comment by harikt** [comment]
I actually noticed one thing. I have accidentally commited something that I have been trying to benchmark :P . I hope I can send a PR if I fix the same in the coming days.

**Comment by sergeyklay** [comment]
Don't worry 😉 Take your time. I'm ok with this

**Pull request merged**
